# Generated by Django 6.0.6 on 2026-07-15 10:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0018_hardwareregistryplatformvendor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardwareregistryplatform",
            name="compatible",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True
            ),
        ),
    ]
